### ISSUE TITLE
Report's not storing in the database when adding MONGO_REPORT_TTL flag in docker-compose

### ISSUE THREAD

**Issue by Sharvin26** [nebula-orchestrator/worker#68]
Hello

The issue is referenced with our discussion here [#63](https://github.com/nebula-orchestrator/worker/issues/63#issuecomment-509173500)

## Expected/Wanted Behavior
Report get's generated and stored in the database as soon as an edge device is updated.

## Actual Behavior
Edge device gets updated but I don't get any report in the database under `nebula_reports` Collection. If I remove the `MONGO_REPORT_TTL` flag report get's stored immediately in the database.

## Steps to Reproduce the Problem

  1. I have configured Reporter, Kafka cluster, ZooKeeper, and Manager on the VPS.
  2. I have configured Worker on the Edge device.
  3. Configured `MONGO_REPORT_TTL: 31536000` for Reporter.

## Specifications

`docker-compose.yml` for Reporter, Kafka cluster, ZooKeeper, and Manager =>

```
version: '3'
services:
  manager:
    container_name: manager
    hostname: manager
    image: nebulaorchestrator/manager
    ports:
      - "80:80"
    restart: unless-stopped
    network_mode: host
    environment:
      MONGO_URL: mongodb://<user_name>:<password>@localhost:27017/nebula
      SCHEMA_NAME: nebula
      BASIC_AUTH_PASSWORD: nebula
      BASIC_AUTH_USER: nebula
      AUTH_TOKEN: nebula

  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: zookeeper:3.4.13
    ports:
      - 2181:2181
    restart: unless-stopped
    environment:
      ZOO_MY_ID: 1

  kafka:
    container_name: kafka
    hostname: kafka
    image: confluentinc/cp-kafka:5.1.2
    ports:
      - 9092:9092
    restart: unless-stopped
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://<my_vps_url>:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  reporter:
    container_name: reporter
    hostname: reporter
    depends_on:
      - kafka
    image: nebulaorchestrator/reporter
    restart: unless-stopped
    network_mode: host
    environment:
      MONGO_URL: mongodb://<user_name>:<password>@localhost:27017/nebula
      SCHEMA_NAME: nebula
      BASIC_AUTH_PASSWORD: nebula
      BASIC_AUTH_USER: nebula
      KAFKA_BOOTSTRAP_SERVERS: localhost:9092
      KAFKA_TOPIC: nebula-reports
      MONGO_REPORT_TTL: 31536000
```

What am I doing wrong here?
